services:
  - type: web
    name: cuenta-ahorros-backend
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/cuenta-ahorros-api-1.0.0.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080 